### ISSUE TITLE
Deploying only to Testflight

### ISSUE THREAD

**Issue by intonarumori** [bitrise-steplib/steps-deploy-to-itunesconnect-deliver#43]
I get the following error using this step:
```
[!] Insufficient permissions for your Apple ID:
	User xxxxxx@xxxxxxx.xxx (Team ID xxxxxxxxx) doesn't have enough permission for the following action: create_version
```

I only have developer permissions on iTunesConnect, but I'm able to deliver Testflight builds with Application Loader.

After searching around I found this issue:
https://github.com/fastlane/fastlane/issues/11079
It seems like Fastlane has a separate lane for Testflight builds.

Is there any way to set up this step to work as Application Loader?

(I was also looking for a Testflight step in the Bitrise workflow editor, but it returned zero results for the `testflight` query)

**Comment by viktorbenei** [comment]
Hi @intonarumori ,

Thanks for creating this issue / feature request!

> Is there any way to set up this step to work as Application Loader?

No, right now this is the only step developed & maintained by us for uploading into TestFlight.

We'll bring this up for a discussion to have an option to not require admin rights. In the meantime a workaround can be to use a Script step and run the `testflight` fastlane action from the Script.

If you'd have any questions just let us know! ;)

**Comment by intonarumori** [comment]
@viktorbenei Thanks for the reply.

Here's the side story: I'm running Bitrise for my personal projects and find it fairly easy to setup.
However, when I work on a client project and want to introduce CI, they usually don't see the immediate benefit and I have to convince them. When it just works out of the box it's fairly easy, because I don't have to spend their money and resources on something they think they don't need.
I can set it up in an hour and they just get used to fresh builds all the time and finally subscribe.

I think it's a very common scenario for developers to only have limited permissions on iTunesConnect so I'm fairly surprised that you guys don't have the Testflight build option out of the box.

Unfortunately I'm facing the task of either setting up a script step myself (which right now I don't want to spend time on), or just look for another provider that has the solution out of the box.

I appreciate your consideration for future development, but you possibly just lost a client.

**Comment by viktorbenei** [comment]
Thanks again for the feedback @intonarumori ! Don't get me wrong, we definitely will discuss this scenario with the team at the next sprint planning! Can't promise any delivery date because we'll have to discuss this first & see when we could fit it into our schedule. We have tons of things we're working on, have to prioritize things :)

**Comment by viktorbenei** [comment]
@intonarumori from a related discussion it seems we might already have a tool for you, which right now is in "deprecated" status but we can remove that. The step I'm referring to is the "Shenzhen" version of this step: https://github.com/bitrise-io/steps-deploy-to-itunesconnect-shenzhen

Did you try that? If not yet, can you try it? It uses Application Launcher which should support uploading the build with only dev permission. In fact we deprecated that step because it doesn't do anything else, just uploads, but that should cover what you want & for that dev permissions should be enough.

You can add the Shenzhen version in yml mode:

```
- deploy-to-itunesconnect-shenzhen: {}
```

or via direct git ref:

```
- git::https://github.com/bitrise-io/steps-deploy-to-itunesconnect-shenzhen.git@master: {}
```

Please let us know how it goes or if you'd have any questions!

**Comment by viktorbenei** [comment]
Hi,

> @viktorbenei I just cannot get it to show up in your workflow editor, tried "shenzhen", "itunesconnect", "deploy". 🤷

Switch to `bitrise.yml` mode/tab in the workflow editor and add this step there:

```
- git::https://github.com/bitrise-io/steps-deploy-to-itunesconnect-shenzhen.git@master: {}
```

Of course you're free to go with another service, although worth to note that CircleCI does not have any built in feature to deploy to the appstores. You'll have to use a 3rd party tool like fastlane which you can use the exact same way on bitrise.io

**Comment by intonarumori** [comment]
Let me remind you guys on your own mission statement:
> Our mission directive is to provide a platform that lets you concentrate on the process of innovation, instead of the byproducts of it.

So does hacking a `yml` file just to get a very basic use case covered align with this? I don't think so.

**Comment by viktorbenei** [comment]
Hi @intonarumori ,

>Let me remind you guys on your own mission statement:
>> Our mission directive is to provide a platform that lets you concentrate on the process of innovation, instead of the byproducts of it.

I think "configure the automation once, then just forget about it" is definitely in line with our mission statement. Yes, in this case it might include a small YML tweak, but the point is still the same: once it's configured it will let you concentrate on the process of innovation instead of doing these tasks manually every time.

> Let me know if you get your act together and we can finally have something that works out of the box, thanks.

Adding that "hidden" step I mentioned should work, "out of the box":

```
- git::https://github.com/bitrise-io/steps-deploy-to-itunesconnect-shenzhen.git@master: {}
```

Once you add the step it'll behave the same way as any other step **on the UI**. So it's only about adding the step in YML mode, once it's in there you can use it on the UI.

Why isn't this step available in the steplib? Because it doesn't provide enough features, based on our stats. Pretty much every user ends up using this step (the Deliver based one) eventually, because it can automate more things.

To be honest I think you're the first one who would rather use that step, which can't do anything else other than uploading, I'm not aware of any other related feedback since we removed that step from the steplib quite a while ago. BUT if you can try that step and it's indeed what you're looking for I can bring it up for a discussion with the team that there's indeed a use case for it. I can't do it without that as the reason of removal from the steplib was maintenance overhead, as the deliver version of the step provides more features.

So, if you can try the shenzhen step (`- git::https://github.com/bitrise-io/steps-deploy-to-itunesconnect-shenzhen.git@master: {}`) and it's indeed what you're looking for please let me know and I'll do my best to get it back to the StepLib as an available step on the UI.

**Comment by viktorbenei** [comment]
Note: if you're interested you can find the related docs about how steps can be referenced in the config here: https://devcenter.bitrise.io/bitrise-cli/steps/#step-referenceid-format

The git one can be found in this sub-section: https://devcenter.bitrise.io/bitrise-cli/steps/#special-step-sources -- it basically defines a git repository to be used as the source, instead of the primary steplib.

**Comment by intonarumori** [comment]
I beg to differ, it's a manual step and completely negates the usefulness of your fancy workflow editor.

If I understand you correctly I should test it for you then when it works subscribe?
This is ridiculous.

Who cares that it's a maintenance cost for you, that's what you get paid for in the for of subscription fees, right?

If you don't know anybody who would need this step then you guys are seriously out of touch with your customers and the iOS developer community.

At this point I rather wait for Apple to do something with Buddybuild.

**Comment by viktorbenei** [comment]
> If I understand you correctly I should test it for you then when it works subscribe?

It's scheduled for a discussion anyway, but if you confirm that step is indeed what you're looking for that would bump this task's priority.

> Who cares that it's a maintenance cost for you, that's what you get paid for in the for of subscription fees, right?

Do you have an active subscription on bitrise.io? If you do that bumps its priority, otherwise we have to consider the priority based on our paying customers' needs.

**Comment by intonarumori** [comment]
Again please let me know if you have a step out of the box within your workflow editor.

I'm pretty sure if you put the same amount of time into creating the step for us you would not only help a lot of freelancers and make your product easier to use, but you would also proove your workflow editor is super easy to integrate with.

You did none of these.

**Comment by intonarumori** [comment]
@viktorbenei I put at least 5 previous clients on Bitrise including some big names.

I think I was clear in my first post what we need.

**Comment by intonarumori** [comment]
And again since Apple has a separate tool for doing exactly what we need (Application loader) how any CI company thinks it's an unessential feature to provide out of the box with an easy UI is still beyond me.

**Comment by philipp-serfling** [comment]
Are there any news on the topic?

We are using Bitrise and it would be really helpful to deploy the testing version of the app only to testflight.

**Comment by fehersanyi-bitrise** [comment]
Hello there @philipp-serfling 

the deliver step crashed due to the 2fa enforcement, and for it is only a fastlane wrapper, we can't do much about it, and the official Apple API is still not out.
Currently you can use the `Deploy to iTunes Connect - Application Loader` step. 🙃

**Comment by philipp-serfling** [comment]
Thx for the quick answer, but the `Deploy to iTunes Connect - Application Loader` step is not able to automatically release the version for external testers after the build was pushed to testflight. 

My current workaround is to use a Script step in Bitrise and use fastlane testflight for it. 

For whom it might help:
```
FASTLANE_USER=$USER FASTLANE_PASSWORD=$PASS FASTLANE_ITC_TEAM_ID=$TEAM_ID fastlane run testflight distribute_external:"true" ipa:$BITRISE_IPA_PATH changelog:"foo" groups:$GROUPS 
```

**Comment by fehersanyi-bitrise** [comment]
Thanks @philipp-serfling for sharing your workaround!

**Comment by mackoj** [comment]
I didn't worked for me :(

Since `Deploy to iTunes Connect` use Fastlane underneath it can use properly my credentials how to share my credentials with my own Fastlane lane ? @fehersanyi-bitrise

**Comment by fehersanyi-bitrise** [comment]
Hy @mackoj in your fastlane lane I guess you set these credentials with environment variables, you could set up those in the env var or secrets tab and run the lane, it will find the credentials in the os.

**Comment by mackoj** [comment]
I tried to add a script execution juste before with
```
envman add --key FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD --value "$CI_APP_PASSWORD"
envman add --key FASTLANE_USER --value "$CI_APPLE_ID"
envman add --key FASTLANE_PASSWORD --value "$CI_APPLE_PASS"
envman add --key FASTLANE_ITC_TEAM_ID --value "$TEAM_ID"
```

And it does not work.

**Comment by fehersanyi-bitrise** [comment]
🤔 Could you send me one of these build's url please?

**Comment by mackoj** [comment]
My bad @fehersanyi-bitrise it fail only on local on remote it's working
