### ISSUE TITLE
Password property is overridden by FASTLANE_PASSWORD

### ISSUE THREAD

**Issue by toineheuvelmans** [bitrise-steplib/steps-deploy-to-itunesconnect-deliver#54]
I have a setup for deploying an iOS app in which at an early point I run a fastlane lane for code signing (which utilizes `match`). The password for `match` (I use `FASTLANE_PASSWORD`) is set in the secret env variables section.
Later on in the workflow the `steps-deploy-to-itunesconnect-deliver` step is used, in which I had specified the Password to be used using another secret env variable. **The user that is used for `deliver` is a different user used for `match`**. This used to work, until I attempted to run the workflow today (after not having used it for a couple of months).
It took me quite a while before I discovered that `deliver` used the password stored in `FASTLANE_PASSWORD` instead of the Password value I had set in the deploy step.
Did something change here? One could argue my setup is suboptimal, but it is confusing that the password value I set through the deploy step is not necessarily the value that is actually used.

**Comment by BirmacherAkos** [comment]
Hi!

Since the v2.14.1 the password input is sensitive (need to be a secret)
[compare/2.13.1...2.14.1](https://github.com/bitrise-io/steps-deploy-to-itunesconnect-deliver/compare/2.13.1...2.14.1#diff-91d8d269a1c9bd3631ddb04b80b01c4eR73)

This could cause the problem.

**Comment by toineheuvelmans** [comment]
Hi @BirmacherAkos, thanks for your reply, though I don't believe it applies to my situation, as I have both passwords already configured as secret.

**Comment by godrei** [comment]
Hi @toineheuvelmans could you please share your failed build url?

**Comment by toineheuvelmans** [comment]
@godrei https://app.bitrise.io/build/db3fac4e3cbc95a2

**Comment by godrei** [comment]
Hi, the thing is that the step sets the provided password as an env var for the deliver command call: https://github.com/bitrise-io/steps-deploy-to-itunesconnect-deliver/blob/master/main.go#L369 (it sets the `DELIVER_PASSWORD` env).

But it seems Fastlane prefers the `FASTLANE_PASSWORD` over `DELIVER_PASSWORD`: https://github.com/fastlane/fastlane/blob/master/credentials_manager/lib/credentials_manager/account_manager.rb#L42 that's why `FASTLANE_PASSWORD` is used if available.

I think to make the step independent from `FASTLANE_PASSWORD` existence, we should clear this env for the deliver command call.

I scheduled a task to fix this, thanks for the report @toineheuvelmans !

**Comment by richard-bogdan-bitrise** [comment]
Hi @toineheuvelmans, thank you for your patience. We updated the code, please check that if the newest release solves your problem (https://github.com/bitrise-steplib/steps-deploy-to-itunesconnect-deliver/releases/tag/2.16.2).
I am closing this issue now, if the issue still persists please feel free to raise a new issue.
