### ISSUE TITLE
Release notes did not get uploaded to TestFlight

### ISSUE THREAD

**Issue by brandtdaniels** [bitrise-steplib/steps-deploy-to-itunesconnect-deliver#75]
Using the command `--release_notes "${CHANGELOG}"` in the options for deliver field, the release notes were printed in the bitrise console during the build, but did not end up appearing in TestFlight when the build was ready to test.

**Comment by bitce** [comment]
Hey @brandtdaniels! 

Can you please include a build URL we could check out? 🙂

**Comment by rickmanelius** [comment]
For us this happened with build 1945 https://app.bitrise.io/build/85fe4d69c791a107#?tab=log. We can see the "delivery summary" containing the "release_notes" key and value, but it doesn't show up in Testflight.

**Comment by rickmanelius** [comment]
Honestly, I'm at a loss how to proceed. Docs here https://docs.fastlane.tools/actions/deliver/ show a pretty straightforward request to localize as follows

```
release_notes({
  'default' => "Shiny and new",
  'de-DE' => "glaenzend und neu"
})
```

However, since I believe this step is passing through via CLI and we're trying to specify the --release_notes flag directly, it's expecting this in a different format that I can't decipher from the examples. https://docs.fastlane.tools/actions/deliver/#cli. And from the `fastlane deliver --help` output, the request is `--release_notes [VALUE] Metadata: Localised release notes for this version`, but I've yet to see a good example of how to do that in my Google searches.

**Comment by non-binary** [comment]
Hi @rickmanelius,

Looking at https://docs.fastlane.tools/actions/deliver/#usage, https://docs.fastlane.tools/actions/deliver/#tips and https://docs.fastlane.tools/actions/deliver/#localized-metadata, I believe the localized release notes need to be in separate files based on language etc and then `fastlane deliver` should grab them automatically.

Can you try this and let me know what the outcome is?

The documentation could be improved though. Once we figure it out, I will probably file a pull request to add a concrete example. Given this is also not related to Bitrise directly but Fastlane, opening a ticket on their support may also be beneficial.

**Comment by non-binary** [comment]
@brandtdaniels Can you share a link to a build as previously requested but also can you provide the contents of `$CHANGELOG`. It's possible that it's a formatting/escape issue.

**Comment by rickmanelius** [comment]
Hi @non-binary Thank you very much for the response. I get the file approach may be best. However, since we are trying to generate the notes at runtime (basically state the branch name and bitrise.io workflow), it's slightly more challenging to have another script to run and export those values to said file vs just use the flag presented. Still, I'll take your advice and go that route because it seems the clearest path forward given that there isn't a specific example in the fastlane docs. I'll also try to submit a suppot request there for their CLI examples and, if they provide one that unblocks me, I'll post it back here.

Thanks!
